//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoYoBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookDetail
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public int book_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual book book { get; set; }
        public virtual member member { get; set; }
    }
}
